### ISSUE TITLE
npmjs version not up-to-date

### ISSUE THREAD

**Issue by cbeckfield** [Vestorly/ember-cli-emblem#15]
Hey, noticed that you're on version 0.2.6 in the repo but npm is still at 0.2.5. Is that intentional? Just wanted to point it out.

**Comment by joebartels** [comment]
thanks @cbeckfield for bringing that up. Seems like an overlook on our part. @jondayton can you verify the version with npm :sunglasses:

**Comment by coladarci** [comment]
:+1: !

**Comment by coladarci** [comment]
@joebartels / @jondayton  - is this just a simple release that's missing? I only ask because I'm about to generate hundreds of files (migrating) and if this isn't going to be released anytime soon, I'd be tempted to generate with the old version then bump the version once my files are in. Thanks for all the emblem work - love that Emblem is being kept alive for ember-cli

**Comment by jondayton** [comment]
@coladarci looks like we got the versions out of sync -- just re-published now so let me know if you have any more issues

**Comment by coladarci** [comment]
Awesome - problem resolved. Thanks a ton for jumping on this..
